version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: url_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener_db
    restart: unless-stopped


  api:
    build: .
    container_name: url_shortener_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    ports:
      - "8002:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: